cozystack/cozystack

- packages/core/platform/Makefile
- packages/core/platform/templates/apps.yaml
`.Capabilities.APIVersions.Has "helm.toolkit.fluxcd.io/v2beta1` does not work for Helm Template, so we must explicity pass apiversions to `helm template` command
see: https://github.com/helm/helm/issues/10760
> Fix: tenant-root domain always overrided to example.org

- packages/system/linstor/templates/satellites.yaml
ZFS requires `readOnlyRootFilesystem: true` and `/run` mount
fixes https://github.com/aenix-io/cozystack/issues/17
> enable ZFS support for LINSTOR

- packages/core/platform/templates/helmreleases.yaml
- scripts/installer.sh
This PR moves imperative logic of flushing redis from installer.sh to be declarative in platform chart.
Thus now redis will be restarted every time when the flux saves a new artifact for helmrelease in cozy-public namespace:
```yaml
values:
kubeapps:
redis:
master:
podAnnotations:
repository.cozystack.io/cozystack-apps: "sha256:29222315d063ffede0e09e3d6a24549b3f818fd025646d52e938f4477098a1d1"
repository.cozystack.io/cozystack-extra: "sha256:77381c0662e86398c8fcf53dfb82535cb328cfea38d1351cb220016e5ebe9ba1"
```
This logic is not critical, and used only to show actual infromation about the charts in our dashboard.
This is temporary solution but still a better than already existing now. Hopefully we'll refactor it in a while.
fixes https://github.com/aenix-io/cozystack/issues/19
> The declarative way to flush redis for our dashboard

- packages/apps/mysql/templates/mariadb.yaml
- packages/core/installer/images/cozystack.json
Fix regression introduced by https://github.com/aenix-io/cozystack/pull/51
Metrics should now be explicitly enabled
> Update mysql helm chart

- packages/extra/monitoring/templates/grafana/grafana.yaml
Grafana uses default ingress class `nginx` specified in ClusterIssuer resource, we need to overwrite it to correct ingress class from namespace annotation
> fix: grafana ingress class

- packages/system/kamaji-etcd/Makefile
- packages/system/kamaji-etcd/charts/kamaji-etcd/templates/_helpers.tpl
- packages/system/kamaji-etcd/patches/remove-plus.patch
Upstream issue https://github.com/clastix/kamaji-etcd/pull/56
it makes sense to remove `+` from minor not only for aws.
We're using Talos Linux and also faced with this problem:
```
Server Version: v1.29.0-rc.1
```
Helm recogizes as `v1.29+` and appends it into image tag
> fix: remove plus in kamaji-etcd image tag

- scripts/package-system.mk
Thanks https://github.com/aenix-io/cozystack/pull/96#discussion_r1576142242 from @stefanprodan, that flux does not tolerate kubectl edits
To avoid this the field managed should be specified. Details:
https://fluxcd.io/flux/faq/#why-are-kubectl-edits-rolled-back-by-flux
> fix: Flux does not tolerate kubectl edits

- packages/apps/Makefile
- packages/extra/Makefile
Workaround for https://github.com/vmware-tanzu/kubeapps/issues/7740
> Fix older versions in dashboard

- packages/system/capi-providers/templates/providers.yaml
- packages/system/kamaji/charts/kamaji/Chart.yaml
- packages/system/kamaji/charts/kamaji/README.md
- packages/system/kamaji/charts/kamaji/crds/datastore.yaml
- packages/system/kamaji/charts/kamaji/crds/tenantcontrolplane.yaml
- packages/system/kamaji/charts/kamaji/templates/etcd_job_preinstall.yaml
- packages/system/kamaji/charts/kamaji/values.yaml
- packages/system/kamaji/values.yaml
This PR updates Kamaji and Cluster API provider to the latest versions
This release includes our fixes:
- https://github.com/clastix/kamaji/pull/408
- https://github.com/clastix/cluster-api-control-plane-provider-kamaji/pull/78
- https://github.com/clastix/cluster-api-control-plane-provider-kamaji/pull/93
- https://github.com/clastix/cluster-api-control-plane-provider-kamaji/pull/95
> Update Kamaji v0.5.0

- packages/apps/kubernetes/templates/kccm/manager.yaml
- packages/core/installer/images/cozystack.json
- packages/core/installer/images/matchbox.json
- packages/extra/etcd/templates/datastore.yaml
- packages/extra/etcd/templates/etcd-cluster.yaml
- packages/system/dashboard/images/kubeapps-apis.json
fixes: https://github.com/aenix-io/cozystack/issues/118
- Fix datastore creation depends on created secrets
- Add basic topologySpreadConstraints
- Fix kubernetes chart post-rendering (ref https://github.com/fluxcd/helm-controller/issues/283#issuecomment-2095818525)
> Fix: kubernetes and etcd-operator issues

- packages/apps/kubernetes-proxmox/.helmignore
- packages/apps/kubernetes-proxmox/Chart.yaml
- packages/apps/kubernetes-proxmox/Makefile
- packages/apps/kubernetes-proxmox/README.md
- packages/apps/kubernetes-proxmox/images/ubuntu-container-disk.json
- packages/apps/kubernetes-proxmox/images/ubuntu-container-disk.tag
- packages/apps/kubernetes-proxmox/images/ubuntu-container-disk/Dockerfile
- packages/apps/kubernetes-proxmox/templates/NOTES.txt
- packages/apps/kubernetes-proxmox/templates/_helpers.tpl
- packages/apps/kubernetes-proxmox/templates/cloud-config.yaml
- packages/apps/kubernetes-proxmox/templates/cluster-autoscaler/deployment.yaml
- packages/apps/kubernetes-proxmox/templates/cluster.yaml
- packages/apps/kubernetes-proxmox/templates/clusterctl.yaml
- packages/apps/kubernetes-proxmox/templates/csi/deploy.yaml
- packages/apps/kubernetes-proxmox/templates/csi/infra-cluster-service-account.yaml
- packages/apps/kubernetes-proxmox/templates/helmreleases/cilium.yaml
- packages/apps/kubernetes-proxmox/templates/helmreleases/csi.yaml
- packages/apps/kubernetes-proxmox/templates/helmreleases/delete.yaml
- packages/apps/kubernetes-proxmox/templates/pccm/manager.yaml
- packages/apps/kubernetes-proxmox/templates/pccm/pccm_role.yaml
- packages/apps/kubernetes-proxmox/templates/pccm/pccm_role_binding.yaml
- packages/apps/kubernetes-proxmox/templates/pccm/pccm_secrets.yaml
- packages/apps/kubernetes-proxmox/templates/pccm/service_account.yaml
- packages/apps/kubernetes-proxmox/values.yaml
Sync changes from Remi implementation
> Add Managed Kubernetes - Proxmox version

- packages/extra/etcd/Chart.yaml
- packages/extra/etcd/templates/etcd-cluster.yaml
- packages/extra/versions_map
This should automatically set quota for 95% from requested size for etcd.
Current default is `2Gi`
details:
https://etcd.io/docs/v3.3/dev-guide/limit/#:~:text=The%20default%20storage%20size%20limit,the%20configured%20value%20exceeds%20it.
> etcd quota backend bytes

- packages/extra/etcd/Chart.yaml
- packages/extra/etcd/templates/etcd-cluster.yaml
- packages/extra/etcd/templates/etcd-defrag.yaml
- packages/extra/versions_map
This PR adds CronJob prameters for autocompact etcd and cronjob for automatic defrag, according to Kubernetes docs
https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#maintaining-etcd-clusters
> etcd: enable autocompact and defrag

- packages/apps/kubernetes/Chart.yaml
- packages/apps/kubernetes/templates/cluster.yaml
- packages/apps/kubernetes/templates/helmreleases/cilium.yaml
- packages/apps/versions_map
This PR solves issues with communication across pods in management cluster with KubeVirt and enables BPF masquerading
> kubernetes: enable bpf masqurade and tunnel based routing for tenant clusters

- packages/core/fluxcd/Makefile
- packages/core/fluxcd/charts/flux2/templates/helm-controller.yaml
- packages/core/fluxcd/charts/flux2/templates/image-automation-controller.yaml
- packages/core/fluxcd/charts/flux2/templates/image-reflector-controller.yaml
- packages/core/fluxcd/charts/flux2/templates/kustomize-controller.yaml
- packages/core/fluxcd/charts/flux2/templates/source-controller.yaml
- packages/system/dashboard/Makefile
- packages/system/dashboard/charts/kubeapps/templates/kubeappsapis/deployment.yaml
Allow using other domains for the cluster
As part of https://github.com/aenix-io/cozystack/issues/141
> fix cluster local

- packages/system/kamaji/values.yaml
This PR make kamaji working on clusters with different than `cluster.local` domain
upsteram issue: https://github.com/clastix/kamaji/pull/467
> kamaji: unhardcode cluster.local domain

- packages/apps/kubernetes/templates/cluster.yaml
Kamaji specifies coredns address `10.96.0.10` by default, since we're using 10.95.0.0/16 service networking we have to specify correct dns address `10.95.0.10`
reported by @kingdonb
upstream issue https://github.com/clastix/kamaji/issues/468
> kubernetes: specify correct dns address

- packages/system/kubeovn/Makefile
This PR disabled image tag version for kube-ovn
> kube-ovn: disable cozystack image tag

- manifests/cozystack-installer.yaml
- packages/apps/http-cache/images/nginx-cache.json
- packages/core/installer/images/cozystack.json
- packages/core/installer/images/cozystack.tag
- packages/core/installer/images/matchbox.json
- packages/system/cilium/images/cilium.tag
- packages/system/dashboard/images/dashboard.tag
- packages/system/dashboard/images/kubeapps-apis.json
- packages/system/dashboard/images/kubeapps-apis.tag
- packages/system/kubeovn/images/kubeovn.json
- packages/system/kubeovn/images/kubeovn.tag
- scripts/installer.sh
- scripts/migrations/3
- etcd: enable autocompact and defrag (#137)
- switched place -maxdepth im Makefiles (#140)
- postgres: fix users and roles (#138)
- kubernetes: enable bpf masqurade and tunnel routing (#144)
- Unhardcode cluster.local domain (#142)
- kamaji: unhardcode cluster.local domain (#145)
- kubernetes: specify correct dns address (#147)
- change hardcode for talos registry (#148)
- Update Cilium v1.15.5
- Update kube-ovn v1.13.0-ge1310e17 and enable image building (#149)
- cilium: enforce device detection and enable image building
- kube-ovn: disable cozystack image tag
> release 0.7.0

- packages/apps/clickhouse/Chart.yaml
- packages/apps/clickhouse/templates/clickhouse.yaml
- packages/apps/versions_map
The Altinity Operator, by default, only allows user logins from localhost. This pull request enables logins from other networks.
> fix clickhouse login

- packages/core/platform/bundles/distro-hosted.yaml
- packages/core/platform/bundles/paas-hosted.yaml
This PR removes kubeovn and cilium dependencies in `*-hosted` bundles
> fix: dependsOn kubeovn and cilium in *-hosted bundles

- packages/extra/ingress/Chart.yaml
- packages/extra/ingress/README.md
- packages/extra/ingress/config.json
- packages/extra/ingress/templates/nginx-ingress.yaml
- packages/extra/ingress/values.schema.json
- packages/extra/ingress/values.yaml
- packages/extra/versions_map
There is a configuration without load-balancer service, when all nodes of the cluster are responsible for routing traffic.
In this case we can provide user an oportunity to specify IP-addresses of the nodes which are used to recieve traffic.
These nodes will be used to route traffic to nginx-ingress pods.
fixes https://github.com/aenix-io/cozystack/issues/158
> Allow specifying externalIPs for ingress-nginx

- hack/e2e.sh
Add script that creates three VMs and installs Cozystack into them
> Add e2e tests

- packages/system/cilium/Makefile
- packages/system/cilium/images/cilium.tag
- packages/system/kubeovn/Makefile
- packages/system/kubeovn/images/kubeovn.tag
Correct kube-ovn tag. There is no such image in registry :
```
ghcr.io/aenix-io/cozystack/kubeovn:v0.7.0
```
but there is:
```
ghcr.io/aenix-io/cozystack/kubeovn:v1.13.0
```
and 
```
ghcr.io/aenix-io/cozystack/kubeovn:v1.13.0-v0.7.0
```
Not critical as we always specify sha-digests, so they should prevail
> fix kubeovn and cilium tags

- packages/core/installer/Makefile
- packages/core/installer/images/cozystack.json
- packages/core/installer/images/cozystack.tag
- packages/core/installer/images/cozystack/Dockerfile
As part of https://github.com/aenix-io/cozystack/issues/27
Thanks [beby.cloud](https://beby.cloud/en/) for providing infrastucture.
Cozystack has been succefully deployed on three Raspbery PIs in minimal configuration:
CNI and kube-proxy used from Talos Linux, cozystack configuration as follows:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: cozystack
namespace: cozy-system
data:
bundle-name: "distro-hosted"
bundle-disable: "etcd-operator"
```
```
NAMESPACE                        NAME                        AGE   READY   STATUS
cozy-cert-manager                cert-manager                65m   True    Helm upgrade succeeded for release cozy-cert-manager/cert-manager.v2 with chart cozy-cert-manager@0.7.0
cozy-cert-manager                cert-manager-issuers        65m   True …
```
> Add initial ARM support

- packages/core/fluxcd/Makefile
- packages/system/dashboard/Makefile
- packages/system/ingress-nginx/Makefile
- packages/system/kamaji-etcd/Makefile
- packages/system/kubeovn/Makefile
Add option `--no-backup-if-mismatch` to every patch command, so it will not create .orig and .diff files anymore
> Use patch with --no-backup-if-mismatch

- packages/system/capi-operator/Makefile
- packages/system/capi-providers/Makefile
- packages/system/cert-manager-issuers/Makefile
- packages/system/cert-manager/Makefile
- packages/system/cilium/Makefile
- packages/system/clickhouse-operator/Makefile
- packages/system/dashboard/Makefile
- packages/system/etcd-operator/Makefile
- packages/system/grafana-operator/Makefile
- packages/system/ingress-nginx/Makefile
- packages/system/kafka-operator/Makefile
- packages/system/kamaji/Makefile
- packages/system/kubeovn/Makefile
- packages/system/kubevirt-cdi-operator/Makefile
- packages/system/kubevirt-cdi/Makefile
- packages/system/kubevirt-operator/Makefile
- packages/system/kubevirt/Makefile
- packages/system/linstor/Makefile
- packages/system/mariadb-operator/Makefile
- packages/system/metallb/Makefile
- packages/system/monitoring/Makefile
- packages/system/piraeus-operator/Makefile
- packages/system/postgres-operator/Makefile
- packages/system/rabbitmq-operator/Makefile
- packages/system/redis-operator/Makefile
- packages/system/telepresence/Makefile
- packages/system/victoria-metrics-operator/Makefile
- scripts/fluxcd-kustomize.sh
- scripts/package-system.mk
This PR introduces a new fluxcd-kustomize.sh script that can be used as post-processor for helm for adding a common fluxcd labels.
This is very useful for `make diff`, so it will not include diff between these labels anymore
Also for debugging specific kustomize cases, eg:
- https://github.com/fluxcd/helm-controller/issues/283
- https://github.com/fluxcd/flux2/issues/4368
> add fluxcd labels post processor

- packages/apps/kubernetes/README.md
- packages/apps/kubernetes/templates/helmreleases/cert-manager.yaml
- packages/apps/kubernetes/templates/helmreleases/delete.yaml
- packages/apps/kubernetes/templates/helmreleases/fluxcd.yaml
- packages/apps/kubernetes/templates/helmreleases/ingress-nginx.yaml
- packages/apps/kubernetes/templates/ingress.yaml
- packages/apps/kubernetes/values.schema.json
- packages/apps/kubernetes/values.yaml
- scripts/installer.sh
- scripts/package-system.mk
Follow up to https://github.com/aenix-io/cozystack/pull/183
* Allows to specify hosts, not just a single host
* fix typo in cert-manager addon
* Addons disabled by default
* Add FluxCD addon
fixes https://github.com/aenix-io/cozystack/issues/159
fixes https://github.com/aenix-io/cozystack/issues/157
fixes https://github.com/aenix-io/cozystack/issues/185
> Update Tenant Kubernetes Addons

- packages/apps/kubernetes/templates/helmreleases/cert-manager.yaml
- packages/apps/kubernetes/templates/helmreleases/cilium.yaml
- packages/apps/kubernetes/templates/helmreleases/csi.yaml
- packages/apps/kubernetes/templates/helmreleases/fluxcd.yaml
- packages/apps/kubernetes/templates/helmreleases/ingress-nginx.yaml
- packages/core/platform/templates/helmreleases.yaml
Fix #195
Don't set the `interval` so short on HelmReleases, with this many HelmReleases that really hamstrings the control plane.
Also, copy the install/upgrade remediation config from system packages to the Kubernetes templates for addon packages (cilium, flux, ingress) - in my testing the ingress-nginx chart fails every time the first time. Maybe that should be filed as a separate issue, I haven't looked into detail, it is some issue related to a secret not being created, I think it said something related to an admission controller.
Looks as though it's a conflict with being installed at the same time as the cert-manager addon.
> Fine-tuning Flux configuration

- packages/core/installer/images/cozystack.json
- scripts/installer.sh
image to test:
```
ghcr.io/aenix-io/cozystack/cozystack:v0.8.0@sha256:48e9f676f4eca5f7036648a56767c31beb0aca8fdc6d6798bd65de74886ed1ef
```
this PR should fix a problem of upgrading from older cozystack version
```
make: Leaving directory '/cozystack/packages/core/platform'
deployment.apps/source-controller condition met
deployment.apps/helm-controller condition met
Error from server (NotFound): helmreleases.helm.toolkit.fluxcd.io "fluxcd" not found
NAME                                        CREATED AT
helmreleases.helm.toolkit.fluxcd.io         2024-05-29T11:00:16Z
helmrepositories.source.toolkit.fluxcd.io   2024-05-29T11:00:17Z
make: Entering directory '/cozystack/packages/system/fluxcd-operator'
kubectl patch hr -n cozy-fluxcd fluxcd-operator -p '{"spec": {"suspend": true}}' …
```
> hotfix: handle missing flux-operator release during upgrade

- packages/system/ingress-nginx/values.yaml
The error manifests as:
W0705 16:07:35.694677       7 configmap.go:431] unexpected error merging defaults: 2 error(s) decoding:
* cannot parse 'proxy-connect-timeout' as int: strconv.ParseInt: parsing "10s": invalid syntax
* cannot parse 'proxy-read-timeout' as int: strconv.ParseInt: parsing "10s": invalid syntax
I came across this trying to understand why my nginx ingress addon config isn't working, (this didn't help, but at least the warning is gone now.)
I'll continue to try to debug, but I think this can merge any time
> Fix nginx config error parsing configmap

- packages/system/ingress-nginx/values.yaml
I don't understand why "true" value isn't accepted here, but I have seen this before. The `--enable-ssl-passthrough` parameter is not supposed to accept any value, it's a stand-alone argument.
With this change I get my traffic appropriately passed through to backend ingress on a kubevirt cluster that enabled TLS
Without it (the change is made on the addon ingress, which is very strange, because that one isn't even configured to use a passthrough annotation... the root ingress controller doesn't seem to care) I get this error:
> 400 Bad Request
> The plain HTTP request was sent to HTTPS port
> ---
> nginx
> Fix nginx error related to passthrough TLS

- packages/apps/kubernetes/templates/cluster.yaml
This PR introduces change to allow upgrading existing node groups for tenant Kubernetes cluster:
This fixes the error:
```
Status: Failed (UpgradeFailed: Helm upgrade failed for release tenant-test0/kubernetes-test0 with chart kubernetes@0.3.0: cannot patch "kubernetes-test0-md0" with kind KubevirtMachineTemplate: admission webhook "validation.kubevirtmachinetemplate.infrastructure.cluster.x-k8s.io" denied the request: KubevirtMachineTemplateSpec is immutable)
```
This is done by generating unique names for KubevirtMachineTemplate based on hash from spec. Old KubevirtMachineTemplates keep existing in the cluster until some MachineSet continues using them.
> kubernetes: Allow upgrading existing node groups

- packages/extra/ingress/Chart.yaml
- packages/extra/ingress/templates/nginx-scrape.yaml
- packages/extra/versions_map
Now grafana dashboards for ingress-nginx controller completely works!
> fix: scraping ingress-nginx metrics

- packages/core/platform/templates/helmreleases.yaml
- scripts/installer.sh
Developers ofthen forget to unsuspend helm releases after the local development (I do!)
This change make ensure that all system helm charts are getting reconciled by flux after cozystack container restart
> Unsuspend system helmreleases on cozystack restart

- packages/system/capi-providers/templates/providers.yaml
Fix wrong version for KubeVirt CAPI provider
> fix kubevirt infrastructure-provider version

- packages/extra/ingress/Chart.yaml
- packages/extra/ingress/templates/nginx-ingress.yaml
- packages/extra/monitoring/Chart.yaml
- packages/extra/monitoring/templates/oncall/oncall-release.yaml
- packages/extra/versions_map
Some software is managed without operator. We store Helm charts for them in system packages and have operator-like logic for installation via FluxCD releases.
This PR changes the name of such releases to have cozy- prefix to have the same standard naming of such charts and do not conflict with user names.
**why is it needed**
Eg. `nats` is not inteneded to be installed via operator, they are prefer the helm-like approach. The same hapening with ingress-nginx controller and grafana-oncall
I purpose to name all of such charts (installed by flux for the user) with `cozy` prefix.
Thus user currently might install user-faced `nats` helm chart with user-specific parameters, later they will be propogated to `cozy-nats` chart managed by FluxCD.
> Rename system releases to have -system suffix

- packages/apps/postgres/Chart.yaml
- packages/apps/postgres/templates/init-script.yaml
- packages/apps/versions_map
This PR refactors postgress configuration script:
- Added event trigger on creating new schemas for automatically set owner
- Refactored logic for fixing permissions for all objects in all schemas
> postgres: automatically set schema permissions

- packages/apps/kubernetes/templates/ingress.yaml
We need to separate HTTP and HTTPS traffic and send them into tenant clusters.
Currently traffic was sending only on HTTPS port, this PR enables HTTP traffic forwarding.
Nginx ingress does not support setting correct upstream according to type of traffic (http or https)
There are set of issues in upstream.
- https://github.com/kubernetes/ingress-nginx/issues/1655
- https://github.com/kubernetes/ingress-nginx/issues/9061
- https://github.com/kubernetes/ingress-nginx/issues/11334
Good to know that we found reliable workaround
fixes: https://github.com/aenix-io/cozystack/issues/209#issuecomment-2215021489
> ingress forward both 80 and 443 ports to tenant clusters

- packages/system/kubeovn/images/kubeovn.json
- packages/system/kubeovn/images/kubeovn.tag
- packages/system/kubeovn/images/kubeovn/Dockerfile
While update isn't possbile for now, let's use workaround, to hardcode older ovn version
- details: https://github.com/aenix-io/cozystack/pull/252
> fix: kubeovn building

- packages/core/platform/bundles/distro-full.yaml
- packages/core/platform/bundles/paas-full.yaml
- packages/system/objectstorage-controller/Chart.yaml
- packages/system/objectstorage-controller/Makefile
- packages/system/objectstorage-controller/templates/controller.yaml
- packages/system/objectstorage-controller/templates/crds.yaml
As part of
- https://github.com/aenix-io/cozystack/pull/131
- https://github.com/seaweedfs/seaweedfs/issues/5838
This controller will be used to provisioning S3 buckets in SeaweedFS
Upstream projects: 
- https://github.com/kubernetes-sigs/container-object-storage-interface-api
- https://github.com/kubernetes-sigs/container-object-storage-interface-controller
Docs:
- https://container-object-storage-interface.github.io/
> add: objectstorage-controller

- Makefile
- packages/system/kamaji/Makefile
- packages/system/kamaji/images/kamaji/Dockerfile
- packages/system/kamaji/images/kamaji/patches/enable-gc.diff
- packages/system/kamaji/values.yaml
upstream issue https://github.com/clastix/kamaji/issues/508 
> fix kamaji garbage collection

- Makefile
- hack/e2e.sh
- packages/core/testing/Chart.yaml
- packages/core/testing/Makefile
- packages/core/testing/images/e2e-sandbox.json
- packages/core/testing/images/e2e-sandbox/Dockerfile
- packages/core/testing/templates/sandbox.yaml
- packages/core/testing/values.yaml
This PR introduces new functionality for running e2e-tests in k8s-cluster.
`make test` from a root invokes deploying of new sandbox for testing cozystack.
from `packages/core/testing`:
`make test` - runs the end-to-end tests.
`make exec` - opens an interactive shell in the sandbox container.
`make login` - downloads the kubeconfig into a temporary directory and runs a shell with the sandbox environment; mirrord must be installed.
`make proxy` - enables a SOCKS5 proxy; mirrord and gost must be installed.
> Add e2e testing sandbox

- packages/system/cilium/values.yaml
This PR enables SCTP support in Cilium.
It is required to use with kube-ovn configuration as it is fixes `externalTrafficPolicy: Local` issues:
- https://github.com/kubeovn/kube-ovn/issues/4457
> cilium: enable SCTP feature

- packages/system/cilium/values.yaml
This PR fixes the error for tenant Kubernetes clusters:
```
Failed to start: daemon creation failed: unable to initialize BPF masquerade support: BPF masquerade requires NodePort
```
> cilium node port

- packages/system/ingress-nginx/values.yaml
Fixed nginx-ingress image to include this patch:
- https://github.com/kubernetes/ingress-nginx/pull/11843
> Nginx-ingress: fix tls-passthrough if ClientHello is fragmented

- packages/apps/kubernetes/images/kubevirt-csi-driver/Dockerfile
Upstream issue: https://github.com/kubevirt/csi-driver/issues/120
Until fixed rollback to older version
> fix grpc address lookup in kubevirt-csi-driver

- manifests/cozystack-installer.yaml
- packages/apps/kubernetes/images/cluster-autoscaler.tag
- packages/apps/kubernetes/images/kubevirt-cloud-provider.tag
- packages/apps/kubernetes/images/kubevirt-csi-driver.tag
- packages/core/installer/values.yaml
- packages/core/testing/values.yaml
- packages/system/dashboard/values.yaml
- packages/system/kamaji/values.yaml
- cilium: Fix tunnel option (#392)
- fix grpc address lookup in kubevirt-csi-driver (#393)
- Prepare release v0.16.2
> Prepare release v0.16.2

- packages/system/capi-operator/values.yaml
> increase capi-operator resources limits

- packages/apps/vm-instance/README.md
- packages/apps/vm-instance/values.schema.json
- packages/apps/vm-instance/values.yaml
> vm-instance: switch default profile to ubuntu

- packages/system/monitoring/values.yaml
It is blocking monitoring installation when monitoring in tenant-root isn't ready yet
> temporary disable readinessProbe

- packages/apps/versions_map
- packages/apps/vm-instance/Chart.yaml
- packages/apps/vm-instance/templates/vm.yaml
- packages/apps/vm-instance/values.yaml
> Update vm-instance to not include vm-disk prefix

- packages/apps/kubernetes/Chart.yaml
- packages/apps/postgres/Chart.yaml
- packages/apps/redis/Chart.yaml
- packages/apps/versions_map
- packages/apps/virtual-machine/Chart.yaml
- packages/apps/vm-instance/Chart.yaml
- packages/extra/etcd/Chart.yaml
- packages/extra/ingress/Chart.yaml
- packages/extra/monitoring/Chart.yaml
- packages/extra/seaweedfs/Chart.yaml
- packages/extra/versions_map
fixes versions update after this pr https://github.com/aenix-io/cozystack/pull/563
> Update version-map for updated application

- pkg/cmd/server/start.go
> Fix openapi spec for cozystack apps

- packages/system/kubeovn/images/kubeovn/Dockerfile
Fix error:
```
E0310 22:22:18.208943  124771 ipsec.go:376] flush ip xfrm policy rule error: fork/exec /usr/sbin/ip: operation not permitted, output:
E0310 22:22:18.208977  124771 ipsec.go:399] flush ip xfrm rules error: fork/exec /usr/sbin/ip: operation not permitted
```
Upstream bug: https://github.com/kubeovn/kube-ovn/issues/4526#issuecomment-2521200770
> kube-ovn: Fix flush ip xfrm policy rule error

- packages/system/cilium/templates/networkpolicy.yaml
- packages/system/cilium/values.yaml
- packages/system/linstor/templates/networkpolicy.yaml
- packages/system/monitoring-agents/templates/networkpolicy.yaml
This commit enables Cilium's host firewall feature and makes use of it to deny external connections to two exporters running as daemonset pods in the host network namespace.
> Enable Cilium host firewall

- packages/core/installer/values.yaml
- packages/system/linstor/templates/cluster.yaml
- packages/system/linstor/templates/satellites-reloader.yaml
this PR fixes problem
```
* admission webhook "vlinstorcluster.kb.io" denied the request: LinstorCluster.piraeus.io "linstorcluster" is invalid: spec.patches.0.patch: Invalid value: "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  annotations:\n    secret.reloader.stakater.com/auto: \"true\"\n": Failed to parse patch as either Strategic Merge Patch (missing metadata.name in object {{apps/v1 Deployment} {{ } map[] map[secret.reloader.stakater.com/auto:true]}}) or JSON Patch (json: cannot unmarshal object into Go value of type jsonpatch.Patch)
```
used solution from
- https://github.com/piraeusdatastore/piraeus-operator/issues/701#issuecomment-2377702085
> [linstor] fix reloader patch

- packages/system/linstor/hack/plunger/plunger-satellite.sh
Sometimes DRBD devices get stuck in "Connecting" state, probably due to some
race conditions. This scriptlet provides a workaround for such situations.
> [linstor] Add plunger check for disconnected DRBD peers.

- .github/workflows/tags.yaml
Let's revert 3c511023f37c78a05e0c57f809490add9c060836, because DCO don't like such commits
> [ci] Revert: Workflows: Use real username to commit changes and fix assets

- packages/system/capi-providers/templates/providers.yaml
Backport of #825 
cherry picked from commit a14bcf98ddc796d6a757b2ffaa2696b3fc5c9260
> [backport] [platform]: make lower resource request for capi-kamaji-controller-manager

- .github/workflows/backport.yaml
- .github/workflows/pull-requests-release.yaml
- .github/workflows/pull-requests.yaml
- .github/workflows/tags.yaml
This PR includes refactored pipeline:
- Automatcially create long-term releasing branch `release-X.Y` after any tag `vX.Y.*` has publushed
- Allow only tags with names `vX.Y.Z` or `vX.Y.Z-rcN`
- Automatically set `prerelease` option for the release if release is candidate
- Automatically set `latest` option for the release according to semver
- Add a new workflow to backport PRs with `backport` label into current feature release
- Do not requrie `ok-to-test` label for internal PRs
> [ci] Enable release-candidates and backport functionality

- .github/workflows/tags.yaml
Backport of #876 to branch `release-0.30`
> [Backport release-0.30] [ci] Fix uploading assets to release

- internal/controller/workload_controller.go
- internal/controller/workload_controller_test.go
- internal/controller/workloadmonitor_controller.go
* Count Workload resources for pods by requests, not limits
* Do not count init container requests
* Prefix Workloads for pods with `pod-`, just like the other types to prevent possible name collisions (closes #787)
The previous version of the WorkloadMonitor controller incorrectly summed resource limits on pods, rather than requests. This prevented it from tracking the resource allocation for pods, which only had requests specified, which is particularly the case for kubevirt's virtual machine pods. Additionally, it counted the limits for all containers, including init containers, which are short-lived and do not contribute much to the total resource usage.
(cherry picked from commit 1e59e5fbb6e009dddec8274c82e185ba2442d338)
Signed-off-by: Timofei Larkin <lllamnyp@gmail.com>
> Fix virtual machine resource tracking (#904)

- packages/extra/ingress/templates/nginx-ingress.yaml
Fix regression introduced by https://github.com/cozystack/cozystack/pull/929#discussion_r2090992853
becasue of `splitList "," "" == [""]`
> [ingress] avoid invalid externalIPs when config value is empty

- packages/extra/ingress/templates/nginx-ingress.yaml
Reverts cozystack/cozystack#957. This was already fixed by https://github.com/cozystack/cozystack/pull/952
> Revert "[ingress] avoid invalid externalIPs when config value is empty"

- packages/system/seaweedfs/values.yaml
```release-note
[seaweedfs] disable proxy-buffering for ingress
```
> [seaweedfs] disable proxy-buffering for ingress

- packages/apps/postgres/Chart.yaml
- packages/apps/postgres/templates/db.yaml
- packages/apps/versions_map
- packages/system/cozystack-api/templates/cozystack-resource-definitions.yaml
This patch populates existing CozystackResourceDefinitions with minimal working examples of secret selectors to take advantage of the newest revision of the ancestor tracking webhook.
```release-note
[platform] Specify secret selectors for existing managed apps in their
respective CozystackResourceDefinitions, which provides the last bit of
information necessary for the lineage webhook to correctly mark secrets
as user-facing or not.
```
> [platform] Add secret selectors to CozyRDs
