- ADOPTERS.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- MAINTAINERS.md
These files are required for applying CNCF Sandbox
https://github.com/cncf/sandbox/issues/87
> Add Adopters, Code of Conduct, Contributing, and Maintainers guides

- README.md
- hack/prepare_release.sh
- packages/core/installer/Makefile
Change tag of matchbox image:
- from `ghcr.io/aenix-io/cozystack/matchbox:${COZYSTACK_VERSION}`
- to `ghcr.io/aenix-io/cozystack/matchbox:${TALOS_VERSION}`
This is first step before moving the documentation to https://cozystack.io/docs/
> Change tag for matchbox image

- packages/core/installer/images/installer/Dockerfile
- packages/core/installer/templates/cozystack.yaml
fixes https://github.com/aenix-io/cozystack/issues/18
> Enable leader election for Cozystack

- README.md
> Positioning Cozystack as framework for building clouds

- packages/apps/http-cache/Makefile
- packages/apps/kubernetes/Makefile
- packages/core/installer/Makefile
- packages/system/dashboard/Makefile
> Prepare release v0.2.0

- README.md
Add link to roadmap on GitHub
ref https://github.com/aenix-io/cozystack-website/issues/4
> Add link to roadmap

- packages/system/piraeus-operator/charts/piraeus/Chart.yaml
- packages/system/piraeus-operator/charts/piraeus/templates/config.yaml
- packages/system/piraeus-operator/charts/piraeus/templates/crds.yaml
- packages/system/piraeus-operator/charts/piraeus/templates/validating-webhook-configuration.yaml
fixes https://github.com/aenix-io/cozystack/issues/42
piraeus-operator v2.4.1
LINSTOR v2.4.1
DRBD 9.2.8
> Update piraeus-operator and LINSTOR v2.4.1

- manifests/cozystack-installer.yaml
- packages/apps/http-cache/images/nginx-cache.json
- packages/apps/kubernetes/images/ubuntu-container-disk.json
- packages/core/installer/images/cozystack.json
- packages/core/installer/images/cozystack.tag
- packages/core/installer/images/matchbox.json
- packages/core/platform/templates/namespaces.yaml
- packages/system/dashboard/images/dashboard.json
- packages/system/dashboard/images/kubeapps-apis.json
- scripts/installer.sh
- scripts/migrations/1
- Bump image versions
- Add extra namespaces
- Kube-OVN migration
> Release 0.2.0

- packages/apps/mysql/Chart.yaml
- packages/apps/mysql/templates/db.yaml
- packages/apps/mysql/templates/mariadb.yaml
- packages/apps/mysql/templates/user.yaml
- packages/apps/versions_map
Fix regression introduced by https://github.com/aenix-io/cozystack/pull/51
CRD names were changed
> Fix mysql app

- packages/apps/clickhouse/Chart.yaml
- packages/apps/clickhouse/templates/clickhouse.yaml
- packages/apps/clickhouse/values.yaml
- packages/apps/versions_map
Part of https://github.com/aenix-io/cozystack/issues/73
> Add application for Clickhouse

- packages/apps/kafka/Chart.yaml
- packages/apps/kafka/templates/kafka.yaml
- packages/apps/kafka/templates/topics.yaml
- packages/apps/kafka/values.yaml
- packages/apps/versions_map
as part of https://github.com/aenix-io/cozystack/issues/72
> Add application for Kafka

- packages/apps/clickhouse/templates/clickhouse.yaml
- packages/apps/clickhouse/values.yaml
as part of https://github.com/aenix-io/cozystack/issues/73
* Add users management
* Remove logs volume
> Update clickhouse app

- hack/package-system.mk
- packages/core/fluxcd/Makefile
- packages/core/installer/Makefile
- packages/core/platform/Makefile
- packages/system/capi-operator/Makefile
- packages/system/capi-providers/Makefile
- packages/system/cert-manager-issuers/Makefile
- packages/system/cert-manager/Makefile
- packages/system/cilium/Makefile
- packages/system/clickhouse-operator/Makefile
- packages/system/dashboard/Makefile
- packages/system/grafana-operator/Makefile
- packages/system/ingress-nginx/Makefile
- packages/system/kafka-operator/Makefile
- packages/system/kamaji/Makefile
- packages/system/kubeovn/Makefile
- packages/system/kubevirt-cdi-operator/Makefile
- packages/system/kubevirt-cdi/Makefile
- packages/system/kubevirt-operator/Makefile
- packages/system/kubevirt/Makefile
- packages/system/linstor/Makefile
- packages/system/mariadb-operator/Makefile
- packages/system/metallb/Makefile
- packages/system/monitoring/Makefile
- packages/system/postgres-operator/Makefile
- packages/system/rabbitmq-operator/Makefile
- packages/system/redis-operator/Makefile
- packages/system/telepresence/Makefile
- packages/system/victoria-metrics-operator/Makefile
I made only the corrections specified in the ticket, other changes related to makefiles will be  made later together with the CI and the build system.
> Refactor Makefiles #83

- packages/system/piraeus-operator/charts/piraeus/Chart.yaml
- packages/system/piraeus-operator/charts/piraeus/templates/config.yaml
- packages/system/piraeus-operator/charts/piraeus/templates/crds.yaml
New version includes a lot of useful fixes, and zfs pools management
https://github.com/LINBIT/linstor-server/releases/tag/v1.27.1
> Update LISNTOR v1.27.1

- packages/apps/kubernetes/templates/cluster-autoscaler/deployment.yaml
- packages/apps/kubernetes/templates/csi/deploy.yaml
- packages/apps/kubernetes/templates/helmreleases/delete.yaml
- packages/apps/kubernetes/templates/kccm/manager.yaml
fixes https://github.com/aenix-io/cozystack/issues/92
> Fix tolerations in Kubernetes chart

- packages/core/installer/templates/cozystack.yaml
> Installer rollout startegy tuned to allow downtime

- packages/system/cilium/charts/cilium/Chart.yaml
- packages/system/cilium/charts/cilium/README.md
- packages/system/cilium/charts/cilium/templates/cilium-envoy/daemonset.yaml
- packages/system/cilium/charts/cilium/values.yaml
- packages/system/cilium/charts/cilium/values.yaml.tmpl
Minor Cilium update v1.14.9 --> v1.14.10
> Update Cilium v1.14.10

- manifests/cozystack-installer.yaml
- packages/apps/http-cache/images/nginx-cache.json
- packages/apps/kubernetes/images/ubuntu-container-disk.json
- packages/apps/mysql/templates/mariadb.yaml
- packages/apps/mysql/templates/secret.yaml
- packages/core/installer/images/cozystack.json
- packages/core/installer/images/cozystack.tag
- packages/core/installer/images/matchbox.json
- packages/system/dashboard/images/dashboard.json
- packages/system/dashboard/images/dashboard.tag
- packages/system/dashboard/images/kubeapps-apis.json
- packages/system/dashboard/images/kubeapps-apis.tag
- scripts/installer.sh
- scripts/migrations/2
This also includes a small fix for mariadb and migration for it
> Prepare release v0.5.0

- packages/apps/kubernetes/Chart.yaml
- packages/apps/kubernetes/templates/cluster.yaml
- packages/apps/versions_map
- Allow root login without password
- add ephemeral volumes for containerd and kubelet
- update kubernetes application
> upd kubernetes

- packages/apps/Makefile
- packages/extra/Makefile
- packages/system/Makefile
When I started to build modules, I got an error with find process it does not allow to build correctly.
> switched place -maxdepth im Makefiles

- packages/apps/postgres/Chart.yaml
- packages/apps/postgres/templates/init-script.yaml
- packages/apps/versions_map
The users and roles get confused between each other in initialization script
> postgres: fix users and roles

- packages/core/installer/Makefile
without this fix can't build project localy
> Change hardcode for talos registry

- packages/core/installer/images/cozystack.json
- packages/core/installer/images/cozystack.tag
- packages/system/dashboard/images/kubeapps-apis.json
- packages/system/dashboard/images/kubeapps-apis.tag
- packages/system/dashboard/images/kubeapps-apis/Dockerfile
- packages/system/dashboard/images/kubeapps-apis/fluxcd.diff
- packages/system/dashboard/images/kubeapps-apis/labels.diff
- packages/system/dashboard/images/kubeapps-apis/reconcile-strategy.diff
This PR enables new flux 2.3.0 support in dashboard
Caravel plagin is currenlty disabled due to dependencies problem
Upstream issue: https://github.com/vmware-tanzu/kubeapps/pull/7847
> Update flux plugin for dashboard

- packages/apps/postgres/Chart.yaml
- packages/apps/postgres/README.md
- packages/apps/postgres/templates/db.yaml
- packages/apps/postgres/values.schema.json
- packages/apps/postgres/values.yaml
- packages/apps/versions_map
> postgres: option to enable quorum-based replication

- packages/apps/kubernetes/templates/helmreleases/ingress-nginx.yaml
- scripts/installer.sh
- scripts/package-system.mk
I am testing install with this PR #183 and I had some issues, these should help
> Tenant nginx ingress (fixes)

- packages/system/etcd-operator/charts/etcd-operator/Chart.yaml
- packages/system/etcd-operator/charts/etcd-operator/README.md
- packages/system/etcd-operator/charts/etcd-operator/README.md.gotmpl
- packages/system/etcd-operator/charts/etcd-operator/crds/etcd-cluster.yaml
- packages/system/etcd-operator/charts/etcd-operator/templates/rbac/clusterrole-manager-role.yml
- packages/system/etcd-operator/charts/etcd-operator/templates/workload/deployment.yml
- packages/system/etcd-operator/charts/etcd-operator/values.schema.json
- packages/system/etcd-operator/charts/etcd-operator/values.yaml
This PR updates etcd-operator to latest version
https://github.com/aenix-io/etcd-operator/releases/tag/v0.3.0
> Update etcd-operator v0.3.0

- packages/apps/kubernetes/Chart.yaml
- packages/apps/kubernetes/Makefile
- packages/apps/kubernetes/images/ubuntu-container-disk.json
- packages/apps/kubernetes/images/ubuntu-container-disk.tag
- packages/apps/kubernetes/images/ubuntu-container-disk/Dockerfile
- packages/apps/kubernetes/templates/cluster.yaml
- packages/apps/kubernetes/templates/helmreleases/delete.yaml
- packages/apps/versions_map
> Upgrade tenant Kubernetes v1.30.1

- manifests/cozystack-installer.yaml
- packages/apps/http-cache/images/nginx-cache.json
- packages/apps/kubernetes/images/ubuntu-container-disk.json
- packages/core/installer/images/cozystack.json
- packages/core/installer/images/cozystack.tag
- packages/core/installer/images/matchbox.json
- packages/extra/ingress/Chart.yaml
- packages/extra/ingress/templates/nginx-scrape.yaml
- packages/extra/versions_map
- packages/system/capi-providers/templates/providers.yaml
- packages/system/cilium/images/cilium.json
- packages/system/dashboard/images/dashboard.json
- packages/system/dashboard/images/dashboard.tag
- packages/system/dashboard/images/kubeapps-apis.json
- packages/system/dashboard/images/kubeapps-apis.tag
- packages/system/kubeovn/images/kubeovn.json
- fix: scraping ingress-nginx metrics (#212)
- fix kubevirt infrastructure-provider version (#225)
- Prepare release v0.9.1
> release 0.9.1

- packages/apps/tenant/templates/networkpolicy.yaml
- packages/extra/ingress/README.md
- packages/extra/ingress/templates/dashboard.yaml
- packages/extra/ingress/values.schema.json
- packages/extra/ingress/values.yaml
Add option to enable dashboard in ingress
> Add option to enable dashboard in ingress-nginx

- packages/apps/kafka/Chart.yaml
- packages/apps/kafka/templates/kafka.yaml
- packages/apps/kafka/templates/topics.yaml
- packages/apps/versions_map
this PR fixes an error:
```spec.replicas: Invalid value: "string": spec.replicas in body must be of type integer```
> Fix Kafka topics creation

- packages/system/etcd-operator/charts/etcd-operator/Chart.yaml
- packages/system/etcd-operator/charts/etcd-operator/templates/rbac/clusterrole-manager-role.yml
This update enables resize operation for etcd clusters
https://github.com/aenix-io/etcd-operator/pull/254
> Update etcd-operator v0.4

- packages/apps/kubernetes/templates/cluster.yaml
- packages/apps/kubernetes/values.yaml
> Fix kubelet garbage collection and introduce ephemeralStorage parameter

- packages/apps/kubernetes/templates/cluster.yaml
fixes https://github.com/aenix-io/cozystack/issues/209
> Kubernetes: fix node-role labels propogation

- packages/extra/monitoring/Chart.yaml
- packages/extra/monitoring/templates/vm/vmalert.yaml
This PR fixes memory charts,
fixes https://github.com/aenix-io/cozystack/issues/285
> Fix vmrules to process memory metrics

- packages/apps/virtual-machine/README.md
- packages/apps/virtual-machine/templates/service.yaml
- packages/apps/virtual-machine/templates/vm.yaml
- packages/apps/virtual-machine/values.schema.json
- packages/apps/virtual-machine/values.yaml
- Refactored `values.yaml` to move disk size under `resources` and added `service.ports` configuration.
- Updated `README.md` to include detailed parameter descriptions and example configuration.
- Modified `service.yaml` to use dynamic port configuration from `values.yaml`.
- Corrected `vm.yaml` to reference disk size from `resources` and updated base image URL for Fedora.
- Revised `values.schema.json` to align with changes in `values.yaml`, including added parameters and descriptions.
Enhancements include:
- Improved clarity of default values and parameter settings.
- Added flexibility for service port customization.
- Corrected and updated URLs and default values for better accuracy.
> Update Virtual Machine Chart Configuration and Documentation

- packages/apps/kubernetes/README.md
- packages/apps/kubernetes/templates/helmreleases/cert-manager.yaml
- packages/apps/kubernetes/templates/helmreleases/fluxcd.yaml
- packages/apps/kubernetes/templates/helmreleases/ingress-nginx.yaml
- packages/apps/kubernetes/values.schema.json
- packages/apps/kubernetes/values.yaml
> Add opportunity to override values for tenant Kubernetes clusters

- manifests/cozystack-installer.yaml
> Prepare release v0.12.0

- packages/apps/postgres/Chart.yaml
- packages/apps/postgres/templates/dashboard-resourcemap.yaml
- packages/apps/postgres/templates/init-script.yaml
- packages/apps/versions_map
> Add passwords generation to postgres

- packages/apps/rabbitmq/Chart.yaml
- packages/apps/rabbitmq/templates/rabbitmq.yaml
> RabbitMQ: fix accessing Kubernetes API when netwrok-policies are enabled

- hack/gen_versions_map.sh
- manifests/cozystack-installer.yaml
- packages/apps/versions_map
- packages/core/installer/values.yaml
- packages/core/testing/values.yaml
- packages/system/dashboard/values.yaml
- packages/system/kamaji/values.yaml
- packages/system/kubeovn/values.yaml
> Prepare release v0.14.1

- Makefile
- packages/apps/clickhouse/Chart.yaml
- packages/apps/clickhouse/Makefile
- packages/apps/clickhouse/README.md
- packages/apps/clickhouse/images/clickhouse-backup.tag
- packages/apps/clickhouse/images/clickhouse-backup/Dockerfile
- packages/apps/clickhouse/templates/backup-cronjob.yaml
- packages/apps/clickhouse/templates/backup-script.yaml
- packages/apps/clickhouse/templates/backup-secret.yaml
- packages/apps/clickhouse/templates/clickhouse.yaml
- packages/apps/clickhouse/values.schema.json
- packages/apps/clickhouse/values.yaml
- packages/apps/ferretdb/images/postgres-backup.tag
- packages/apps/ferretdb/templates/backup-cronjob.yaml
- packages/apps/http-cache/Chart.yaml
- packages/apps/http-cache/Makefile
- packages/apps/mysql/Chart.yaml
- packages/apps/mysql/Makefile
- packages/apps/mysql/images/mariadb-backup.tag
- packages/apps/mysql/images/mariadb-backup/Dockerfile
- packages/apps/mysql/templates/backup-cronjob.yaml
- packages/apps/postgres/Chart.yaml
- packages/apps/postgres/Makefile
- packages/apps/postgres/images/postgres-backup.tag
- packages/apps/postgres/images/postgres-backup/Dockerfile
- packages/apps/postgres/templates/backup-cronjob.yaml
- Add backups for ClickHouse
- Fix backups for MariaDB, Postgres and FerretDB
- Fix HTTP-cache image tag
- Update infromation about backups
> Fix backups

- manifests/cozystack-installer.yaml
- packages/apps/clickhouse/images/clickhouse-backup.tag
- packages/apps/ferretdb/images/postgres-backup.tag
- packages/apps/http-cache/images/nginx-cache.tag
- packages/apps/mysql/images/mariadb-backup.tag
- packages/apps/postgres/images/postgres-backup.tag
- packages/apps/versions_map
- packages/core/installer/values.yaml
- packages/core/testing/values.yaml
- packages/system/dashboard/values.yaml
- packages/system/kamaji/values.yaml
- packages/system/kubeovn/values.yaml
> Prepare release v0.15.0

- packages/system/ingress-nginx/values.yaml
> Update ingress-nginx v1.11.2

- packages/extra/monitoring/templates/grafana/grafana.yaml
> Grafana remove flant-statusmap-panel plugin

- packages/system/seaweedfs/Makefile
- packages/system/seaweedfs/charts/seaweedfs/values.yaml
- packages/system/seaweedfs/values.yaml
Upstream fix:
- https://github.com/seaweedfs/seaweedfs-cosi-driver/pull/1
- https://github.com/seaweedfs/seaweedfs/pull/6074
> Seaweedfs: Fix attributes for bucket creation

- packages/system/cilium/charts/cilium/Chart.yaml
- packages/system/cilium/charts/cilium/README.md
- packages/system/cilium/charts/cilium/templates/cilium-envoy/daemonset.yaml
- packages/system/cilium/charts/cilium/templates/cilium-envoy/service.yaml
- packages/system/cilium/charts/cilium/templates/cilium-operator/deployment.yaml
- packages/system/cilium/charts/cilium/templates/validate.yaml
- packages/system/cilium/charts/cilium/values.yaml
- packages/system/cilium/images/cilium/Dockerfile
- packages/system/cilium/values-kubeovn.yaml
- packages/system/cilium/values.yaml
This PR includes the upstream fix:
- https://github.com/kubeovn/kube-ovn/pull/4575
> Update Cilium v1.16.2 and enable genev_sys_6081 interface

- packages/system/fluxcd/values.yaml
> Update fluxcd v2.4.0

- packages/system/kamaji/images/kamaji/Dockerfile
- packages/system/kamaji/images/kamaji/patches/disable-datastore-check.diff
> Disable Kamaji default datastore check

- packages/core/platform/bundles/distro-full.yaml
fixes https://github.com/aenix-io/cozystack/issues/383
> cilium: enable native routing in distro-full bundle

- packages/system/monitoring/alerts/node-exporter.yaml
to show node hostname instead of ip address
> fix node-exporter alerts

- packages/apps/kubernetes/Chart.yaml
- packages/apps/kubernetes/templates/helmreleases/cilium.yaml
- packages/apps/versions_map
> cilium: Fix tunnel option

- packages/extra/monitoring/templates/alerta/alerta.yaml
- packages/extra/monitoring/templates/grafana/grafana.yaml
> Fix ingress for grafana and alerta

- packages/apps/kubernetes/images/kubevirt-csi-driver/Dockerfile
> Update KubeVirt CSI Driver

- packages/extra/seaweedfs/templates/seaweedfs.yaml
> fix specifying domainName for seaweedfs filer

- hack/e2e.sh
- manifests/cozystack-installer.yaml
- packages/apps/kubernetes/images/cluster-autoscaler.tag
- packages/apps/kubernetes/images/kubevirt-cloud-provider.tag
- packages/apps/kubernetes/images/kubevirt-csi-driver.tag
- packages/core/installer/values.yaml
- packages/core/testing/values.yaml
- packages/extra/seaweedfs/Chart.yaml
- packages/extra/versions_map
- packages/system/dashboard/values.yaml
- packages/system/kamaji/values.yaml
- packages/system/kubeovn/values.yaml
> Prepare release v0.16.3

- packages/system/capi-operator/values.yaml
same as https://github.com/aenix-io/cozystack/pull/400, second try 
fixes https://github.com/aenix-io/cozystack/issues/414
> Fix cluster-api operator resources

- packages/apps/kubernetes/Chart.yaml
- packages/apps/kubernetes/templates/cluster.yaml
- packages/apps/versions_map
> Kubernetes: increase timeouts for CNI initiation

- scripts/installer.sh
> Unsuspend all cozystack charts on start

- packages/core/platform/templates/namespaces.yaml
> fix namespaces creation

- packages/apps/ferretdb/Chart.yaml
- packages/apps/ferretdb/templates/init-script.yaml
- packages/apps/versions_map
> Enhance FerretDB healtcheck during initialization

- packages/apps/vpn/templates/service.yaml
> vpn: fix externalTrafficPolicy

- packages/system/piraeus-operator/charts/piraeus/Chart.yaml
- packages/system/piraeus-operator/charts/piraeus/templates/config.yaml
- packages/system/piraeus-operator/charts/piraeus/templates/crds.yaml
> Update LINSTOR v1.29.1

- packages/core/installer/images/talos/profiles/initramfs.yaml
- packages/core/installer/images/talos/profiles/installer.yaml
- packages/core/installer/images/talos/profiles/iso.yaml
- packages/core/installer/images/talos/profiles/kernel.yaml
- packages/core/installer/images/talos/profiles/metal.yaml
- packages/core/installer/images/talos/profiles/nocloud.yaml
> Update Talos Linux v1.8.1

- packages/system/kubeovn/images/kubeovn/Dockerfile
- packages/system/kubeovn/images/kubeovn/patches/disable-nm-syncer.diff
> kube-ovn add disable-nm-syncer patch

- packages/system/piraeus-operator/charts/piraeus/templates/config.yaml
Reverts aenix-io/cozystack#465
> Revert "Update LINSTOR v1.29.2"

- hack/e2e.sh
- manifests/cozystack-installer.yaml
- packages/apps/clickhouse/images/clickhouse-backup.tag
- packages/apps/ferretdb/images/postgres-backup.tag
- packages/apps/http-cache/images/nginx-cache.tag
- packages/apps/kubernetes/images/cluster-autoscaler.tag
- packages/apps/kubernetes/images/kubevirt-cloud-provider.tag
- packages/apps/kubernetes/images/kubevirt-csi-driver.tag
- packages/apps/kubernetes/images/ubuntu-container-disk.tag
- packages/apps/mysql/images/mariadb-backup.tag
- packages/apps/postgres/images/postgres-backup.tag
- packages/core/installer/values.yaml
- packages/core/testing/values.yaml
- packages/system/bucket/images/s3manager.tag
- packages/system/cilium/values.yaml
- packages/system/cozystack-api/values.yaml
- packages/system/dashboard/values.yaml
- packages/system/kamaji/values.yaml
- packages/system/kubeovn/values.yaml
- scripts/installer.sh
- scripts/migrations/7
- scripts/migrations/8
> Prepare release v0.20.0

- hack/e2e.sh
- packages/core/installer/images/talos/profiles/initramfs.yaml
- packages/core/installer/images/talos/profiles/installer.yaml
- packages/core/installer/images/talos/profiles/iso.yaml
- packages/core/installer/images/talos/profiles/kernel.yaml
- packages/core/installer/images/talos/profiles/metal.yaml
- packages/core/installer/images/talos/profiles/nocloud.yaml
- packages/core/testing/images/e2e-sandbox/Dockerfile
- packages/core/testing/values.yaml
> update Talos Linux v1.8.4

- packages/system/kubeovn/Makefile
- packages/system/kubeovn/charts/kube-ovn/Chart.yaml
- packages/system/kubeovn/charts/kube-ovn/values.yaml
- packages/system/kubeovn/images/kubeovn/Dockerfile
- packages/system/kubeovn/values.yaml
> Update Kube-OVN v1.13.2

- Makefile
- hack/e2e.sh
- manifests/cozystack-installer.yaml
- packages/apps/clickhouse/images/clickhouse-backup.tag
- packages/apps/ferretdb/images/postgres-backup.tag
- packages/apps/http-cache/images/nginx-cache.tag
- packages/apps/kubernetes/images/cluster-autoscaler.tag
- packages/apps/kubernetes/images/kubevirt-cloud-provider.tag
- packages/apps/kubernetes/images/kubevirt-csi-driver.tag
- packages/apps/kubernetes/images/ubuntu-container-disk.tag
- packages/apps/mysql/images/mariadb-backup.tag
- packages/apps/postgres/images/postgres-backup.tag
- packages/core/installer/values.yaml
- packages/core/platform/bundles/distro-full.yaml
- packages/core/platform/bundles/distro-hosted.yaml
- packages/core/platform/bundles/paas-full.yaml
- packages/core/platform/bundles/paas-hosted.yaml
- packages/core/testing/values.yaml
- packages/system/bucket/images/s3manager.tag
- packages/system/cilium/values.yaml
- packages/system/cozystack-api/values.yaml
- packages/system/cozystack-controller/values.yaml
- packages/system/dashboard/charts/kubeapps/templates/dashboard/configmap.yaml
- packages/system/dashboard/values.yaml
- packages/system/kamaji/values.yaml
- packages/system/kubeovn/values.yaml
> Prepare release v0.22.0

- packages/core/builder/values.yaml
- packages/core/installer/images/talos/profiles/initramfs.yaml
- packages/core/installer/images/talos/profiles/installer.yaml
- packages/core/installer/images/talos/profiles/iso.yaml
- packages/core/installer/images/talos/profiles/kernel.yaml
- packages/core/installer/images/talos/profiles/metal.yaml
- packages/core/installer/images/talos/profiles/nocloud.yaml
fixes https://github.com/aenix-io/cozystack/issues/541
> Update Talos Linux v1.9.2

- packages/system/dashboard/images/dashboard/Dockerfile
- packages/system/dashboard/images/kubeapps-apis/Dockerfile
This PR includes fix for dashboard
https://github.com/aenix-io/kubeapps/commit/dd02680d796c962b8dcc4e5ea70960a846c1acdc
> Fix dashboard error: Unable to get installed package

- manifests/cozystack-installer.yaml
- packages/apps/http-cache/images/nginx-cache.tag
- packages/apps/kubernetes/images/cluster-autoscaler.tag
- packages/apps/kubernetes/images/kubevirt-cloud-provider.tag
- packages/apps/kubernetes/images/kubevirt-csi-driver.tag
- packages/apps/kubernetes/images/ubuntu-container-disk.tag
- packages/core/installer/values.yaml
- packages/core/testing/values.yaml
- packages/extra/bootbox/images/matchbox.tag
- packages/extra/monitoring/images/grafana.tag
- packages/system/bucket/images/s3manager.tag
- packages/system/cozystack-api/values.yaml
- packages/system/cozystack-controller/values.yaml
- packages/system/dashboard/charts/kubeapps/templates/dashboard/configmap.yaml
- packages/system/dashboard/values.yaml
- packages/system/kamaji/values.yaml
- packages/system/kubeovn/values.yaml
> Prepare release v0.24.1

- packages/system/kubeovn/Makefile
- packages/system/kubeovn/images/kubeovn/Dockerfile
- packages/system/kubeovn/values.yaml
> Upd: kubeovn v1.13.3

- packages/apps/versions_map
- packages/apps/vm-disk/Chart.yaml
- packages/apps/vm-disk/templates/dv.yaml
> [vm-disk] disable immediate bind for non-upload disks

- packages/core/installer/images/talos/profiles/initramfs.yaml
- packages/core/installer/images/talos/profiles/installer.yaml
- packages/core/installer/images/talos/profiles/iso.yaml
- packages/core/installer/images/talos/profiles/kernel.yaml
- packages/core/installer/images/talos/profiles/metal.yaml
- packages/core/installer/images/talos/profiles/nocloud.yaml
> Update Talos Linux to v1.9.5

- packages/core/installer/values.yaml
- packages/core/platform/bundles/distro-full.yaml
- packages/core/platform/bundles/paas-full.yaml
> Fix dependency for clickhouse-operator

- packages/core/installer/values.yaml
- packages/core/platform/bundles/distro-full.yaml
- packages/core/platform/bundles/distro-hosted.yaml
- packages/core/platform/bundles/paas-full.yaml
- packages/core/platform/bundles/paas-hosted.yaml
> fix dependencies for kafka-operator and clickhouse-operator

- packages/core/installer/Makefile
> [ci] Add talos-kernel and talos-initramfs to assets

- .github/workflows/tags.yaml
> [ci] Automatically run tests as part of release pipepline

- .github/workflows/tags.yaml
> [ci] Fix: do not run tests in case of release skipped

- packages/core/platform/templates/helmreleases.yaml
fixes https://github.com/cozystack/cozystack/issues/832
This PR fixes regression on installing helmreleases, also some refactor
> [platform] Fix installing HelmReleases on initial setup

- packages/system/cilium/charts/cilium/Chart.yaml
- packages/system/cilium/charts/cilium/README.md
- packages/system/cilium/charts/cilium/values.yaml
- packages/system/cilium/images/cilium/Dockerfile
> Update Cilium to v1.17.3

- hack/e2e.sh
Backport of #865 to release 0.30
> [Backport release-0.30] [ci,dx] Suppress wget progress bar 

- packages/apps/kubernetes/templates/helmreleases/ingress-nginx.yaml
- packages/apps/kubernetes/templates/helmreleases/vertical-pod-autoscaler.yaml
- [kubernetes] Refactor controlPlane settings
- [ci] Fix uploading assets to release
> [kubernetes] Fix merging valuesOverride for tenant clusters

- packages/system/kubeovn/Makefile
> [kube-ovn] fix versions mapping in Makefile

- .github/workflows/tags.yaml
> [ci] fix release branch creation

- packages/apps/kubernetes/Makefile
> [kubernetes] Fix ubuntu-container-disk tag

- .github/workflows/tags.yaml
> [ci] fix triggering releasing pr tests

- packages/core/platform/bundles/paas-full.yaml
- packages/core/platform/bundles/paas-hosted.yaml
- packages/core/platform/templates/_helpers.tpl
- packages/core/platform/templates/helmreleases.yaml
> [platform] refactor dashboard values

- .github/workflows/pull-requests-release.yaml
> [ci] Fix download released artifacts

- hack/e2e-cluster.bats
> [tests] fix: increase qemu system disk size

- packages/core/platform/templates/_helpers.tpl
- packages/system/dashboard/images/dashboard/Dockerfile
- packages/system/dashboard/images/kubeapps-apis/Dockerfile
- packages/system/dashboard/values.yaml
- [dashboard] Cumulative update (#1042)
- [dashboard] Remove dependency on linsting secrets (#1066)
> [Backport release-0.31] Dashboard update and fixes

- packages/apps/tenant/Chart.yaml
- packages/apps/tenant/charts/cozy-lib
- packages/apps/tenant/templates/tenant.yaml
- packages/apps/versions_map
- packages/library/cozy-lib/Chart.yaml
- packages/library/cozy-lib/templates/_checkinput.tpl
- packages/library/cozy-lib/templates/_cozyconfig.tpl
- packages/library/cozy-lib/templates/_rbac.tpl
- packages/library/cozy-lib/templates/_resourcepresets.tpl
- packages/library/cozy-lib/templates/_resources.tpl
- scripts/migrations/13
Partial backport of https://github.com/cozystack/cozystack/pull/1067
> [Backport release-0.31] Refactor roles and permissions for tenants

- packages/apps/clickhouse/Chart.yaml
- packages/apps/clickhouse/values.yaml
- packages/apps/kafka/Chart.yaml
- packages/apps/kafka/values.yaml
- packages/apps/versions_map
> [clickhouse][kafka] increase resources

- packages/apps/kubernetes/templates/ingress.yaml
> [kubernetes] fix ingress template

- packages/core/platform/bundles/distro-full.yaml
- packages/core/platform/bundles/paas-full.yaml
- packages/system/nfs-driver/.helmignore
- packages/system/nfs-driver/Chart.yaml
- packages/system/nfs-driver/Makefile
- packages/system/nfs-driver/charts/csi-driver-nfs/.helmignore
- packages/system/nfs-driver/charts/csi-driver-nfs/Chart.yaml
- packages/system/nfs-driver/charts/csi-driver-nfs/templates/NOTES.txt
- packages/system/nfs-driver/charts/csi-driver-nfs/templates/_helpers.tpl
- packages/system/nfs-driver/charts/csi-driver-nfs/templates/crd-csi-snapshot.yaml
- packages/system/nfs-driver/charts/csi-driver-nfs/templates/csi-nfs-controller.yaml
- packages/system/nfs-driver/charts/csi-driver-nfs/templates/csi-nfs-driverinfo.yaml
- packages/system/nfs-driver/charts/csi-driver-nfs/templates/csi-nfs-node.yaml
- packages/system/nfs-driver/charts/csi-driver-nfs/templates/csi-snapshot-controller.yaml
- packages/system/nfs-driver/charts/csi-driver-nfs/templates/rbac-csi-nfs.yaml
- packages/system/nfs-driver/charts/csi-driver-nfs/templates/rbac-snapshot-controller.yaml
- packages/system/nfs-driver/charts/csi-driver-nfs/templates/snapshotclass.yaml
- packages/system/nfs-driver/charts/csi-driver-nfs/templates/storageclass.yaml
- packages/system/nfs-driver/charts/csi-driver-nfs/values.yaml
- packages/system/nfs-driver/tests/pvc.yaml
- packages/system/nfs-driver/tests/sc.yaml
- packages/system/nfs-driver/values.yaml
This PR adds a new optional module to support nfs shares
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
labels:
cozystack.io/system: "true"
pod-security.kubernetes.io/enforce: privileged
name: cozy-nfs-driver
spec:
finalizers:
- kubernetes
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
labels:
cozystack.io/repository: system
cozystack.io/system-app: "true"
name: nfs-driver
namespace: cozy-nfs-driver
spec:
chart:
spec:
chart: cozy-nfs-driver
reconcileStrategy: Revision
sourceRef:
kind: HelmRepository
name: cozystack-system
namespace: cozy-system
version: '>= 0.0.0-0'
dependsOn:
- name: cilium
namespace: cozy-cilium
- name: kubeovn
namespace: cozy-kubeovn
install:
crds: CreateReplace
remediation:
retries: -1 …
```
> [nfs-driver] Introduce new module

- packages/system/piraeus-operator/charts/piraeus/Chart.yaml
- packages/system/piraeus-operator/charts/piraeus/templates/config.yaml
- packages/system/piraeus-operator/charts/piraeus/templates/crds.yaml
```release-note
[linstor] Update LINSTOR v1.31.2
```
> [linstor] Update LINSTOR v1.31.2

- packages/system/kubeovn/Makefile
- packages/system/kubeovn/charts/kube-ovn/Chart.yaml
- packages/system/kubeovn/charts/kube-ovn/values.yaml
- packages/system/kubeovn/images/kubeovn/Dockerfile
```release-note
[kube-ovn] Update Kube-OVN v1.13.14
```
> [kube-ovn] Update Kube-OVN v1.13.14

- packages/system/dashboard/images/dashboard/Dockerfile
- packages/system/dashboard/images/kubeapps-apis/Dockerfile
```release-note
[dashboard] swap visual editor and YAML editor; fix handling multiline string
```
> [dashboard] swap visual editor and YAML editor; fix handling multiline string

- packages/system/linstor/templates/podscrape.yaml
> Fix linstor metrics node label
